steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull Image'
    args:
      - 'pull'
      - $_IMAGETAG
      
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Save Tar'
    entrypoint: 'bash'
    args:
      - 'c'
      - |
        docker save -o /workspace/image.tar $_IMAGETAG
        ls -l /workspace

  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload tar'
    args:
      - 'cp'
      - '/workspace/image.tar'
      - 'gs://images-push-test/dummyspring.tar'
options:
  logging: CLOUD_LOGGING_ONLY
